### ISSUE TITLE
How to use this on Windows?

### ISSUE THREAD

**Issue by beerisgood** [Nitrokey/nitrokey-keepass-plugin#2]
How can we use that plugin for KeePass in Windows?

The readme is a empty file and all other files now 3 years old. Does it work with current KeePass?

**Comment by jans23** [comment]
Its not workable right away and would require some development. In particular it would require to use the latest pkcs11interop. It should be relatively easy to get it working.

**Comment by beerisgood** [comment]
Any changes here?

**Comment by jans23** [comment]
We recommend to use another KeePass plugin as described [here](https://www.nitrokey.com/documentation/applications#a:password-manager).

**Comment by beerisgood** [comment]
Can be closed then
