### ISSUE TITLE
No documentation

### ISSUE THREAD

**Issue by rugk** [Nitrokey/nitrokey-keepass-plugin#3]
You have not documented this at all anywhere. Nobody has any idea what this does?

Can you possibly improve that?

**Comment by szszszsz** [comment]
Hi @rugk !
As far as I can tell, this is currently an abandoned project. Indeed this should be described in its Readme.

Related: https://github.com/Nitrokey/nitrokey-keepass-plugin/issues/2

**Comment by rugk** [comment]
Okay, so then: https://github.com/Nitrokey/nitrokey-keepass-plugin/issues/4

**Comment by szszszsz** [comment]
@rugk Please see the [Readme] file, and let me know, whether this answers your questions.

[Readme]: https://github.com/Nitrokey/nitrokey-keepass-plugin/blob/master/README.md

**Comment by szszszsz** [comment]
Ahh, I have missed your latest comment. Will consider archiving it.

**Comment by szszszsz** [comment]
Closing as done. Please reopen otherwise.
